### ISSUE TITLE
Return default prediction when horoskopy are down

### ISSUE THREAD

**Issue by kozaktomas** [kozaktomas/horoskopycli#2]
Time to time maintainers of horoskopy.cz do things like a failover location test. During this period `horoskopycli` usually does not work. It would be nice to return some kind of default prediction.

``` bash
$ horoskopycli vahy
2024/06/25 12:07:49 Could not find contant element
```

**Comment by FUSAKLA** [comment]
Could you please make it print ASCII version of the "this is fine" meme? :pray:

**Comment by kozaktomas** [comment]
Sounds good! I guess we can use the meme from here - https://github.com/NaAbAsD/this_is_fine

Labeling the issue as `good first issue`. Might be good for newcomers.

**Comment by FUSAKLA** [comment]
here you go https://github.com/kozaktomas/horoskopycli/pull/3
